name: Build metapackage
on:
  push:
    branches:
      - main
    paths:
      - metapackage/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install dpkg-dev
      - run: dpkg-deb --build metapackage
      - uses: actions/upload-artifact@v4
        with:
          name: deb
          path: metapackage.deb
          compression-level: 0
