name: Build metapackage
on:
  push:
    branches:
      - main
    paths:
      - metapackage/**
      - .github/workflows/metapackage.yml
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get install dpkg-dev
      - run: dpkg-deb --build metapackage
      - uses: actions/upload-artifact@v4
        with:
          name: deb
          path: metapackage.deb
          compression-level: 0
      - uses: randomairborne/godsvagn-upload@dce6f43bb5179a7b68e6f3743f26ed8477bac961
        with:
          regenerate_url: https://apt-submit.valk.sh/regenerate

